export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';

export const ERROR = 'ERROR';


export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ADDING_TASK = 'ADDING_TASK';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';

export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';

export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';

